exports.all = [
	'core/Entity.js'
	'core/Transform.js'
	'core/SpecParser.js'
	'core/RenderNode.js'
	'core/EventEmitter.js'
	'core/EventHandler.js'
	'core/ElementAllocator.js'

	'utilities/Utility.js'
	'utilities/KeyCodes.js'
	'utilities/Timer.js'

	'transitions/MultipleTransition.js'
	'transitions/TweenTransition.js'
	'transitions/Transitionable.js'
	'transitions/TransitionableTransform.js'

	'core/Context.js'
	'core/OptionsManager.js'
	'core/Engine.js'
	'core/ElementOutput.js'
	'core/Surface.js'
	'core/Group.js'

	# 'transitions/TransitionableTransform' # r.js-optimized position (which is to say, it fell back to alphabetical - as did most of them in fact, as I suspected they would)

	'core/Modifier.js'
	'core/Scene.js'
	'core/View.js'
	'core/ViewSequence.js'

	'events/EventArbiter.js'
	'events/EventFilter.js'
	'events/EventMapper.js'

	'inputs/FastClick.js'
	'inputs/GenericSync.js'
	'inputs/MouseSync.js'
	'inputs/TwoFingerSync.js'
	'inputs/PinchSync.js'
	'inputs/RotateSync.js'
	'inputs/ScaleSync.js'
	'inputs/ScrollSync.js'
	'inputs/TouchTracker.js'
	'inputs/TouchSync.js'

	'math/Vector.js'
	'math/Matrix.js'
	'math/Quaternion.js'
	'math/Random.js'
	'math/Utilities.js'

	'modifiers/Draggable.js'
	'modifiers/Fader.js'
	'modifiers/ModifierChain.js'
	'modifiers/StateModifier.js'

	'physics/integrators/SymplecticEuler.js'
	'physics/bodies/Particle.js'
	'physics/bodies/Body.js'
	'physics/bodies/Circle.js'
	'physics/bodies/Rectangle.js'
	'physics/constraints/Constraint.js'
	'physics/constraints/Collision.js'
	'physics/constraints/Curve.js'
	'physics/constraints/Distance.js'
	'physics/constraints/Snap.js'
	'physics/constraints/Surface.js'
	'physics/constraints/Wall.js'
	'physics/constraints/Walls.js'
	'physics/forces/Force.js'
	'physics/forces/Drag.js'
	'physics/forces/Repulsion.js'
	'physics/forces/RotationalDrag.js'
	'physics/forces/Spring.js'
	'physics/forces/RotationalSpring.js'
	'physics/forces/VectorField.js'
	'physics/PhysicsEngine.js'

	'surfaces/CanvasSurface.js'
	'surfaces/ContainerSurface.js'
	'surfaces/FormContainerSurface.js'
	'surfaces/ImageSurface.js'
	'surfaces/InputSurface.js'
	'surfaces/SubmitInputSurface.js'
	'surfaces/TextareaSurface.js'
	'surfaces/VideoSurface.js'

	'transitions/CachedMap.js'
	'transitions/Easing.js'
	'transitions/SnapTransition.js'
	'transitions/SpringTransition.js'
	'transitions/WallTransition.js'

	# 'utilities/KeyCodes' # r.js-optimized position (which is to say, it fell back to alphabetical - as did most of them in fact, as I suspected they would)
	# 'utilities/Timer' # r.js-optimized position (which is to say, it fell back to alphabetical - as did most of them in fact, as I suspected they would)

	'views/SequentialLayout.js'
	'views/Deck.js'
	'views/RenderController.js'
	'views/EdgeSwapper.js'
	'views/FlexibleLayout.js'
	'views/Flipper.js'
	'views/GridLayout.js'
	'views/HeaderFooterLayout.js'
	'views/Lightbox.js'
	'views/Scroller.js'
	'views/Scrollview.js'
	'views/ScrollContainer.js'

	'widgets/NavigationBar.js'
	'widgets/Slider.js'
	'widgets/ToggleButton.js'
	'widgets/TabBar.js'
]
