exports.include = [
	"famous/core/Context.js"
	"famous/core/ElementAllocator.js"
	"famous/core/Engine.js"
	"famous/core/Entity.js"
	"famous/core/EventEmitter.js"
	"famous/core/EventHandler.js"
	"famous/core/Group.js"
	"famous/core/Modifier.js"
	"famous/core/OptionsManager.js"
	"famous/core/RenderNode.js"
	"famous/core/Scene.js"
	"famous/core/SpecParser.js"
	"famous/core/Surface.js"
	"famous/core/Transform.js"
	"famous/core/View.js"
	"famous/core/ViewSequence.js"

	"famous/events/EventArbiter.js"
	"famous/events/EventFilter.js"
	"famous/events/EventMapper.js"

	"famous/inputs/FastClick.js"
	"famous/inputs/GenericSync.js"
	"famous/inputs/MouseSync.js"
	"famous/inputs/PinchSync.js"
	"famous/inputs/RotateSync.js"
	"famous/inputs/ScaleSync.js"
	"famous/inputs/ScrollSync.js"
	"famous/inputs/TouchSync.js"
	"famous/inputs/TouchTracker.js"
	"famous/inputs/TwoFingerSync.js"

	"famous/math/Matrix.js"
	"famous/math/Quaternion.js"
	"famous/math/Random.js"
	"famous/math/Utilities.js"
	"famous/math/Vector.js"

	"famous/modifiers/Draggable.js"
	"famous/modifiers/Fader.js"
	"famous/modifiers/ModifierChain.js"
	"famous/modifiers/StateModifier.js"

	"famous/physics/bodies/Body.js"
	"famous/physics/bodies/Circle.js"
	"famous/physics/bodies/Particle.js"
	"famous/physics/bodies/Rectangle.js"

	"famous/physics/constraints/Collision.js"
	"famous/physics/constraints/Constraint.js"
	"famous/physics/constraints/Curve.js"
	"famous/physics/constraints/Distance.js"
	"famous/physics/constraints/Snap.js"
	"famous/physics/constraints/Surface.js"
	"famous/physics/constraints/Wall.js"
	"famous/physics/constraints/Walls.js"

	"famous/physics/forces/Drag.js"
	"famous/physics/forces/Force.js"
	"famous/physics/forces/Repulsion.js"
	"famous/physics/forces/RotationalDrag.js"
	"famous/physics/forces/RotationalSpring.js"
	"famous/physics/forces/Spring.js"
	"famous/physics/forces/VectorField.js"

	"famous/physics/integrators/SymplecticEuler.js"

	"famous/physics/PhysicsEngine.js"

	"famous/surfaces/CanvasSurface.js"
	"famous/surfaces/ContainerSurface.js"
	"famous/surfaces/FormContainerSurface.js"
	"famous/surfaces/ImageSurface.js"
	"famous/surfaces/InputSurface.js"
	"famous/surfaces/SubmitInputSurface.js"
	"famous/surfaces/TextareaSurface.js"
	"famous/surfaces/VideoSurface.js"

	"famous/transitions/CachedMap.js"
	"famous/transitions/Easing.js"
	"famous/transitions/MultipleTransition.js"
	"famous/transitions/SnapTransition.js"
	"famous/transitions/SpringTransition.js"
	"famous/transitions/Transitionable.js"
	"famous/transitions/TransitionableTransform.js"
	"famous/transitions/TweenTransition.js"
	"famous/transitions/WallTransition.js"

	"famous/utilities/KeyCodes.js"
	"famous/utilities/Timer.js"
	"famous/utilities/Utility.js"

	"famous/views/Deck.js"
	"famous/views/EdgeSwapper.js"
	"famous/views/FlexibleLayout.js"
	"famous/views/Flipper.js"
	"famous/views/GridLayout.js"
	"famous/views/HeaderFooterLayout.js"
	"famous/views/Lightbox.js"
	"famous/views/RenderController.js"
	"famous/views/ScrollContainer.js"
	"famous/views/Scroller.js"
	"famous/views/Scrollview.js"
	"famous/views/SequentialLayout.js"

	"famous/widgets/NavigationBar.js"
	"famous/widgets/Slider.js"
	"famous/widgets/TabBar.js"
	"famous/widgets/ToggleButton.js"
]